
export const FETCH_SYMBOL_REQUEST = "FETCH_SYMBOL_REQUEST";
export const FETCH_SYMBOL_SUCCESS = "FETCH_SYMBOL_SUCCESS";
export const FETCH_SYMBOL_FAILURE = "FETCH_SYMBOL_FAILURE";

export const SET_LOGIN = "SET_LOGIN";